### ISSUE TITLE
Why aren't the sampling offsets related parameters trained during fine-tuning?

### ISSUE THREAD

**Issue by Michaell109** [ZhangGongjie/Meta-DETR#34]
Dear auther,
I notice that the sampling offsets related parameters aren't trained during fine-tuning. I am kind of confusing what the reason for. 
Looking forward to your reply.

**Comment by ZhangGongjie** [comment]
Thank you for your meticulous attention to detail! That's really a good question!

Just from my experience (very subjective), the sampling offsets related parameters are very sensitive. That's probably why the authors of Deformable-DETR train them with 0.1x learning rates. From my understanding, the sampling offsets are class-agnostic, so fine-tuning them on a very small few-shot dataset probably won't help to achieve better results, and may even degrade the performance due to the small number of training images during fine-tuning. That's why I chose to not train the sampling offsets related parameters.

You may conduct experiments to verify whether my intuition is true. 

Thank you!     ; )

**Comment by Michaell109** [comment]
Thanks very much. Yeah, I have conducted experiments and got the same phenomenon. The statement of "the sampling offsets are class-agnostic“ is really helpful.
