### ISSUE TITLE
num_feature_levels == 4很多地方还没有实现，显示NotImplementedError，请问有完整版的代码吗

### ISSUE THREAD

**Issue by tongxiaortx** [ZhangGongjie/Meta-DETR#39]
num_feature_levels == 4很多地方还没有实现，显示NotImplementedError，请问有完整版的代码吗

**Comment by ZhangGongjie** [comment]
感谢关注。 最初版本的Meta-DETR实现了多尺度特征，但是论文被拒了。后期我们加了correlational meta-learning （见最新的T-PAMI论文 [2208.00219] Meta-DETR: Image-Level Few-Shot Detection with Inter-Class Correlation Exploitation (arxiv.org)），这里我们没有用多尺度特征。 目前开源的代码是最新的TPAMI版本的，所以我们也不会再加多尺度特征了。您可以考虑自己实现，但是可能需要比较大的GPU内存才能跑。 祝好！ 张功杰   From: tongxiaortxSent: Thursday, August 18, 2022 11:09 AMTo: ZhangGongjie/Meta-DETRCc: SubscribedSubject: [ZhangGongjie/Meta-DETR] num_feature_levels == 4很多地方还没有实现，显示NotImplementedError，请问有完整版的代码吗 (Issue #39) num_feature_levels == 4很多地方还没有实现，显示NotImplementedError，请问有完整版的代码吗—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by ZhangGongjie** [comment]
kindly refer to the latest version of the paper, where multi-scale features are not used.
